-- EastShop test catalog seed.
-- Re-runnable: only old/new seed product IDs are replaced. Manually created products are not deleted.

insert into public.categories (id, name_zh, name_en, name_ru, sort_order, is_active)
values
  ('11111111-1111-4111-8111-111111111111', '工业地面', 'Industrial flooring', 'Промышленные полы', 1, true),
  ('22222222-2222-4222-8222-222222222222', '安全装备', 'Safety equipment', 'Средства защиты', 2, true),
  ('33333333-3333-4333-8333-333333333333', '仓储工具', 'Warehouse tools', 'Складские инструменты', 3, true)
on conflict (id) do update
set
  name_zh = excluded.name_zh,
  name_en = excluded.name_en,
  name_ru = excluded.name_ru,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

delete from public.products
where id in (
  'esd-floor-tile-600',
  'epoxy-floor-kit',
  'heavy-duty-pu-mortar-floor',
  'anti-static-warning-tape',
  'insulated-gloves-12kv',
  'anti-fog-safety-goggles',
  'abs-safety-helmet',
  'kn95-dust-mask-50',
  'led-work-light-50w',
  'stackable-storage-bin',
  'laser-distance-meter',
  'ratchet-cargo-strap-5t',
  'conductive-vinyl-roll',
  'raised-access-floor-panel',
  'epoxy-primer-set',
  'anti-static-wrist-strap',
  'nitrile-coated-gloves',
  'safety-face-shield',
  'foldable-platform-cart',
  'stacking-parts-crate',
  'magnetic-led-inspection-light',
  'digital-laser-level'
);

insert into public.products (
  id,
  category_id,
  name_zh,
  name_en,
  name_ru,
  description_zh,
  description_en,
  description_ru,
  detail_zh,
  detail_en,
  detail_ru,
  cover_image,
  cover_images,
  images,
  specs,
  variants,
  tags,
  sort_order,
  is_featured,
  is_active
)
values
  (
    'conductive-vinyl-roll',
    '11111111-1111-4111-8111-111111111111',
    '导电 PVC 卷材地板',
    'Conductive PVC Vinyl Roll',
    'Проводящий ПВХ рулонный пол',
    '适合电子装配线、实验室和服务器机房的连续铺装地材。',
    'Continuous flooring for electronics lines, labs, and server rooms.',
    'Рулонное покрытие для электроники, лабораторий и серверных.',
    '卷材接缝少，易清洁，建议配合导电胶、铜箔和接地系统施工。',
    'Fewer seams, easy cleaning, and recommended with conductive adhesive, copper tape, and grounding.',
    'Меньше швов, простая уборка, рекомендуется монтаж с проводящим клеем, медной лентой и заземлением.',
    '/mock/product-images/conductive-vinyl-roll/cover.svg',
    '["/mock/product-images/conductive-vinyl-roll/cover.svg"]'::jsonb,
    '["/mock/product-images/conductive-vinyl-roll/detail-1.svg","/mock/product-images/conductive-vinyl-roll/detail-2.svg"]'::jsonb,
    '[{"id":"thickness","label":{"zh":"厚度","en":"Thickness","ru":"Толщина"},"value":{"zh":"2.0 mm","en":"2.0 mm","ru":"2.0 мм"}},{"id":"width","label":{"zh":"卷宽","en":"Roll width","ru":"Ширина рулона"},"value":{"zh":"2 m","en":"2 m","ru":"2 м"}}]'::jsonb,
    '[{"id":"10m","name":{"zh":"10 米/卷","en":"10 m roll","ru":"10 м/рулон"},"price":126,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"CVR-10M"},{"id":"20m","name":{"zh":"20 米/卷","en":"20 m roll","ru":"20 м/рулон"},"price":238,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"CVR-20M"}]'::jsonb,
    '["ESD","PVC","roll"]'::jsonb,
    1,
    true,
    true
  ),
  (
    'raised-access-floor-panel',
    '11111111-1111-4111-8111-111111111111',
    '全钢防静电活动地板',
    'Steel Raised Access Floor Panel',
    'Стальная антистатическая фальшпанель',
    '适合数据中心、弱电机房和洁净控制室的架空地板。',
    'Raised floor panel for data centers, equipment rooms, and clean control rooms.',
    'Фальшпол для дата-центров, аппаратных и чистых помещений.',
    '钢板结构承载稳定，表面耐磨，便于布线、检修和后期维护。',
    'Stable steel structure with wear-resistant finish for cabling, inspection, and maintenance.',
    'Прочная стальная конструкция с износостойкой поверхностью для кабелей и обслуживания.',
    '/mock/product-images/raised-access-floor-panel/cover.svg',
    '["/mock/product-images/raised-access-floor-panel/cover.svg"]'::jsonb,
    '["/mock/product-images/raised-access-floor-panel/detail-1.svg","/mock/product-images/raised-access-floor-panel/detail-2.svg"]'::jsonb,
    '[{"id":"size","label":{"zh":"尺寸","en":"Size","ru":"Размер"},"value":{"zh":"600 x 600 mm","en":"600 x 600 mm","ru":"600 x 600 мм"}},{"id":"load","label":{"zh":"集中载荷","en":"Concentrated load","ru":"Сосредоточенная нагрузка"},"value":{"zh":"4450 N","en":"4450 N","ru":"4450 Н"}}]'::jsonb,
    '[{"id":"bare","name":{"zh":"裸板","en":"Bare panel","ru":"Панель без покрытия"},"price":18.6,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"RAF-BARE"},{"id":"hpl","name":{"zh":"HPL 面层","en":"HPL finish","ru":"HPL покрытие"},"price":24.8,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"RAF-HPL"}]'::jsonb,
    '["raised floor","data center"]'::jsonb,
    2,
    true,
    true
  ),
  (
    'epoxy-primer-set',
    '11111111-1111-4111-8111-111111111111',
    '环氧地坪底涂套装',
    'Epoxy Floor Primer Set',
    'Комплект эпоксидной грунтовки',
    '用于混凝土地面封闭和增强附着力的双组份底涂。',
    'Two-component primer for sealing concrete floors and improving adhesion.',
    'Двухкомпонентная грунтовка для бетона и улучшения адгезии.',
    '适合防静电地坪、耐磨地坪和车间翻新项目，施工前需清理浮灰和油污。',
    'Suitable for ESD floors, wear-resistant floors, and workshop renovation. Clean dust and oil before use.',
    'Подходит для антистатических и износостойких полов, а также ремонта цехов.',
    '/mock/product-images/epoxy-primer-set/cover.svg',
    '["/mock/product-images/epoxy-primer-set/cover.svg"]'::jsonb,
    '["/mock/product-images/epoxy-primer-set/detail-1.svg","/mock/product-images/epoxy-primer-set/detail-2.svg"]'::jsonb,
    '[{"id":"coverage","label":{"zh":"覆盖面积","en":"Coverage","ru":"Покрытие"},"value":{"zh":"30-40 平方米/套","en":"30-40 m2/set","ru":"30-40 м2/комплект"}},{"id":"mix","label":{"zh":"配比","en":"Mix ratio","ru":"Соотношение"},"value":{"zh":"A:B = 2:1","en":"A:B = 2:1","ru":"A:B = 2:1"}}]'::jsonb,
    '[{"id":"standard","name":{"zh":"标准型","en":"Standard","ru":"Стандарт"},"price":42,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"EPS-STD"},{"id":"fast-dry","name":{"zh":"快干型","en":"Fast dry","ru":"Быстросохнущий"},"price":49,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"EPS-FD"}]'::jsonb,
    '["epoxy","primer"]'::jsonb,
    3,
    false,
    true
  ),
  (
    'anti-static-wrist-strap',
    '22222222-2222-4222-8222-222222222222',
    '防静电腕带套装',
    'Anti-static Wrist Strap Kit',
    'Комплект антистатического браслета',
    '用于电子维修、装配和检测工位的人体静电释放。',
    'Personal grounding kit for electronics repair, assembly, and inspection stations.',
    'Заземляющий комплект для ремонта, сборки и контроля электроники.',
    '腕带柔软可调，配鳄鱼夹和接地线，适合产线人员日常佩戴。',
    'Adjustable soft wrist strap with alligator clip and grounding cord for daily production use.',
    'Регулируемый браслет с зажимом и проводом заземления для производства.',
    '/mock/product-images/anti-static-wrist-strap/cover.svg',
    '["/mock/product-images/anti-static-wrist-strap/cover.svg"]'::jsonb,
    '["/mock/product-images/anti-static-wrist-strap/detail-1.svg","/mock/product-images/anti-static-wrist-strap/detail-2.svg"]'::jsonb,
    '[{"id":"cord","label":{"zh":"线长","en":"Cord length","ru":"Длина кабеля"},"value":{"zh":"1.8 m","en":"1.8 m","ru":"1.8 м"}},{"id":"resistance","label":{"zh":"保护电阻","en":"Safety resistor","ru":"Защитный резистор"},"value":{"zh":"1 MΩ","en":"1 Mohm","ru":"1 МОм"}}]'::jsonb,
    '[{"id":"single","name":{"zh":"单人套装","en":"Single kit","ru":"Один комплект"},"price":2.9,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"AWS-1"},{"id":"pack10","name":{"zh":"10 套装","en":"Pack of 10","ru":"10 комплектов"},"price":24,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"AWS-10"}]'::jsonb,
    '["ESD","wrist strap"]'::jsonb,
    4,
    true,
    true
  ),
  (
    'nitrile-coated-gloves',
    '22222222-2222-4222-8222-222222222222',
    '丁腈涂层防滑手套',
    'Nitrile Coated Grip Gloves',
    'Перчатки с нитриловым покрытием',
    '适合仓库拣货、设备装配和轻型搬运的耐磨手套。',
    'Durable grip gloves for warehouse picking, equipment assembly, and light handling.',
    'Износостойкие перчатки для склада, сборки и легких работ.',
    '掌面丁腈涂层提升抓握力，透气针织手背适合长时间佩戴。',
    'Nitrile palm coating improves grip, while breathable knit backing supports long wear.',
    'Нитриловое покрытие улучшает захват, дышащая основа удобна для долгой работы.',
    '/mock/product-images/nitrile-coated-gloves/cover.svg',
    '["/mock/product-images/nitrile-coated-gloves/cover.svg"]'::jsonb,
    '["/mock/product-images/nitrile-coated-gloves/detail-1.svg","/mock/product-images/nitrile-coated-gloves/detail-2.svg"]'::jsonb,
    '[{"id":"sizes","label":{"zh":"尺码","en":"Sizes","ru":"Размеры"},"value":{"zh":"M / L / XL","en":"M / L / XL","ru":"M / L / XL"}},{"id":"package","label":{"zh":"包装","en":"Package","ru":"Упаковка"},"value":{"zh":"12 双/包","en":"12 pairs/bag","ru":"12 пар/пакет"}}]'::jsonb,
    '[{"id":"m","name":{"zh":"M 码","en":"Size M","ru":"Размер M"},"price":5.8,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"NCG-M"},{"id":"l","name":{"zh":"L 码","en":"Size L","ru":"Размер L"},"price":5.8,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"NCG-L"},{"id":"xl","name":{"zh":"XL 码","en":"Size XL","ru":"Размер XL"},"price":6.2,"sortOrder":3,"isDefault":false,"isActive":true,"sku":"NCG-XL"}]'::jsonb,
    '["gloves","PPE"]'::jsonb,
    5,
    false,
    true
  ),
  (
    'safety-face-shield',
    '22222222-2222-4222-8222-222222222222',
    '透明防护面屏',
    'Clear Safety Face Shield',
    'Прозрачный защитный щиток',
    '适合打磨、切割、喷溅防护和日常巡检。',
    'Face protection for grinding, cutting, splash protection, and daily inspection.',
    'Защита лица при шлифовке, резке, брызгах и ежедневных проверках.',
    '大视野透明面屏，头箍可调，可与口罩和护目镜组合使用。',
    'Wide clear visor with adjustable headband, compatible with masks and safety goggles.',
    'Широкий прозрачный экран с регулируемым оголовьем, совместим с масками и очками.',
    '/mock/product-images/safety-face-shield/cover.svg',
    '["/mock/product-images/safety-face-shield/cover.svg"]'::jsonb,
    '["/mock/product-images/safety-face-shield/detail-1.svg","/mock/product-images/safety-face-shield/detail-2.svg"]'::jsonb,
    '[{"id":"material","label":{"zh":"材质","en":"Material","ru":"Материал"},"value":{"zh":"PET","en":"PET","ru":"PET"}},{"id":"thickness","label":{"zh":"面屏厚度","en":"Visor thickness","ru":"Толщина экрана"},"value":{"zh":"0.5 mm","en":"0.5 mm","ru":"0.5 мм"}}]'::jsonb,
    '[{"id":"single","name":{"zh":"单个装","en":"Single piece","ru":"1 шт"},"price":3.5,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"SFS-1"},{"id":"box20","name":{"zh":"20 个/箱","en":"20 pcs/box","ru":"20 шт/коробка"},"price":58,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"SFS-20"}]'::jsonb,
    '["face shield","safety"]'::jsonb,
    6,
    false,
    true
  ),
  (
    'foldable-platform-cart',
    '33333333-3333-4333-8333-333333333333',
    '折叠式静音平板车',
    'Folding Silent Platform Cart',
    'Складная бесшумная платформенная тележка',
    '适合仓库、门店和办公室搬运箱包物料。',
    'Platform cart for moving boxes and supplies in warehouses, shops, and offices.',
    'Тележка для коробок и материалов на складе, в магазине и офисе.',
    '折叠扶手节省空间，静音轮减少地面噪音，适合频繁周转。',
    'Foldable handle saves space and quiet wheels reduce noise during frequent handling.',
    'Складная ручка экономит место, тихие колеса снижают шум при перевозке.',
    '/mock/product-images/foldable-platform-cart/cover.svg',
    '["/mock/product-images/foldable-platform-cart/cover.svg"]'::jsonb,
    '["/mock/product-images/foldable-platform-cart/detail-1.svg","/mock/product-images/foldable-platform-cart/detail-2.svg"]'::jsonb,
    '[{"id":"platform","label":{"zh":"台面尺寸","en":"Platform size","ru":"Размер платформы"},"value":{"zh":"720 x 480 mm","en":"720 x 480 mm","ru":"720 x 480 мм"}},{"id":"load","label":{"zh":"载重","en":"Load capacity","ru":"Грузоподъемность"},"value":{"zh":"150 kg","en":"150 kg","ru":"150 кг"}}]'::jsonb,
    '[{"id":"150kg","name":{"zh":"150kg 标准款","en":"150kg standard","ru":"150 кг стандарт"},"price":36,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"FPC-150"},{"id":"300kg","name":{"zh":"300kg 加强款","en":"300kg heavy duty","ru":"300 кг усиленная"},"price":62,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"FPC-300"}]'::jsonb,
    '["cart","warehouse"]'::jsonb,
    7,
    true,
    true
  ),
  (
    'stacking-parts-crate',
    '33333333-3333-4333-8333-333333333333',
    '加厚可堆叠零件箱',
    'Heavy-duty Stackable Parts Crate',
    'Усиленный штабелируемый ящик',
    '用于五金件、电子料和维修备件分类收纳。',
    'Storage crate for hardware, electronic parts, and maintenance spares.',
    'Ящик для метизов, электронных деталей и запасных частей.',
    '前开口方便拿取，支持多色分类，适合货架和工位使用。',
    'Front opening supports quick access and color-coded sorting for shelves and workstations.',
    'Передний доступ и цветовая сортировка для стеллажей и рабочих мест.',
    '/mock/product-images/stacking-parts-crate/cover.svg',
    '["/mock/product-images/stacking-parts-crate/cover.svg"]'::jsonb,
    '["/mock/product-images/stacking-parts-crate/detail-1.svg","/mock/product-images/stacking-parts-crate/detail-2.svg"]'::jsonb,
    '[{"id":"size","label":{"zh":"尺寸","en":"Size","ru":"Размер"},"value":{"zh":"350 x 220 x 160 mm","en":"350 x 220 x 160 mm","ru":"350 x 220 x 160 мм"}},{"id":"material","label":{"zh":"材质","en":"Material","ru":"Материал"},"value":{"zh":"PP","en":"PP","ru":"PP"}}]'::jsonb,
    '[{"id":"blue","name":{"zh":"蓝色","en":"Blue","ru":"Синий"},"price":4.2,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"SPC-BL"},{"id":"yellow","name":{"zh":"黄色","en":"Yellow","ru":"Желтый"},"price":4.2,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"SPC-YE"}]'::jsonb,
    '["storage","crate"]'::jsonb,
    8,
    false,
    true
  ),
  (
    'magnetic-led-inspection-light',
    '33333333-3333-4333-8333-333333333333',
    '磁吸式 LED 检修灯',
    'Magnetic LED Inspection Light',
    'Магнитный LED инспекционный фонарь',
    '适合设备检修、夜间巡检和临时照明。',
    'Portable light for equipment repair, night inspection, and temporary lighting.',
    'Переносной фонарь для ремонта оборудования, ночного осмотра и временного освещения.',
    '底部磁吸可固定在金属表面，支持 USB 充电和多角度调节。',
    'Magnetic base attaches to metal surfaces, with USB charging and multi-angle adjustment.',
    'Магнитное основание крепится к металлу, USB зарядка и регулировка угла.',
    '/mock/product-images/magnetic-led-inspection-light/cover.svg',
    '["/mock/product-images/magnetic-led-inspection-light/cover.svg"]'::jsonb,
    '["/mock/product-images/magnetic-led-inspection-light/detail-1.svg","/mock/product-images/magnetic-led-inspection-light/detail-2.svg"]'::jsonb,
    '[{"id":"brightness","label":{"zh":"亮度","en":"Brightness","ru":"Яркость"},"value":{"zh":"800 lm","en":"800 lm","ru":"800 лм"}},{"id":"runtime","label":{"zh":"续航","en":"Runtime","ru":"Время работы"},"value":{"zh":"4-6 h","en":"4-6 h","ru":"4-6 ч"}}]'::jsonb,
    '[{"id":"single","name":{"zh":"单灯","en":"Single light","ru":"Один фонарь"},"price":13.5,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"MIL-1"},{"id":"kit","name":{"zh":"双灯套装","en":"Two-light kit","ru":"Комплект из 2"},"price":24.6,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"MIL-2"}]'::jsonb,
    '["LED","inspection"]'::jsonb,
    9,
    true,
    true
  ),
  (
    'digital-laser-level',
    '33333333-3333-4333-8333-333333333333',
    '数字激光水平仪',
    'Digital Laser Level',
    'Цифровой лазерный уровень',
    '用于地坪施工、货架安装和设备定位的辅助测量工具。',
    'Measurement tool for flooring work, shelf installation, and equipment positioning.',
    'Измерительный инструмент для полов, стеллажей и позиционирования оборудования.',
    '支持水平垂直双线投射，带数字角度显示，便于现场快速校准。',
    'Projects horizontal and vertical lines with digital angle display for quick on-site alignment.',
    'Горизонтальная и вертикальная линии с цифровым углом для быстрой настройки.',
    '/mock/product-images/digital-laser-level/cover.svg',
    '["/mock/product-images/digital-laser-level/cover.svg"]'::jsonb,
    '["/mock/product-images/digital-laser-level/detail-1.svg","/mock/product-images/digital-laser-level/detail-2.svg"]'::jsonb,
    '[{"id":"range","label":{"zh":"工作距离","en":"Working range","ru":"Рабочая дальность"},"value":{"zh":"30 m","en":"30 m","ru":"30 м"}},{"id":"accuracy","label":{"zh":"精度","en":"Accuracy","ru":"Точность"},"value":{"zh":"+/- 1.5 mm","en":"+/- 1.5 mm","ru":"+/- 1.5 мм"}}]'::jsonb,
    '[{"id":"red","name":{"zh":"红光款","en":"Red beam","ru":"Красный луч"},"price":29,"sortOrder":1,"isDefault":true,"isActive":true,"sku":"DLL-R"},{"id":"green","name":{"zh":"绿光款","en":"Green beam","ru":"Зеленый луч"},"price":39,"sortOrder":2,"isDefault":false,"isActive":true,"sku":"DLL-G"}]'::jsonb,
    '["laser","level"]'::jsonb,
    10,
    false,
    true
  )
on conflict (id) do update
set
  category_id = excluded.category_id,
  name_zh = excluded.name_zh,
  name_en = excluded.name_en,
  name_ru = excluded.name_ru,
  description_zh = excluded.description_zh,
  description_en = excluded.description_en,
  description_ru = excluded.description_ru,
  detail_zh = excluded.detail_zh,
  detail_en = excluded.detail_en,
  detail_ru = excluded.detail_ru,
  cover_image = excluded.cover_image,
  cover_images = excluded.cover_images,
  images = excluded.images,
  specs = excluded.specs,
  variants = excluded.variants,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active;

notify pgrst, 'reload schema';
