insert into public.categories (id, name_zh, name_en, name_ru, sort_order, is_active)
values
  ('11111111-1111-4111-8111-111111111111', '工业地面', 'Industrial flooring', 'Промышленные полы', 1, true),
  ('22222222-2222-4222-8222-222222222222', '安全装备', 'Safety equipment', 'Средства защиты', 2, true),
  ('33333333-3333-4333-8333-333333333333', '仓储工具', 'Warehouse tools', 'Складские инструменты', 3, true)
on conflict (id) do update
set
  name_zh = excluded.name_zh,
  name_en = excluded.name_en,
  name_ru = excluded.name_ru,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = timezone('Asia/Shanghai', now());

insert into public.products (
  id,
  category_id,
  name_zh,
  name_en,
  name_ru,
  description_zh,
  description_en,
  description_ru,
  detail_zh,
  detail_en,
  detail_ru,
  price,
  cover_image,
  images,
  specs,
  tags,
  sort_order,
  is_featured,
  is_active
)
values
  (
    'esd-floor-tile-600',
    '11111111-1111-4111-8111-111111111111',
    'PVC 防静电地板 600x600',
    'PVC ESD Floor Tile 600x600',
    'ПВХ антистатическая плитка 600x600',
    '适合电子厂、机房和洁净车间的耐磨防静电地面材料。',
    'Durable anti-static flooring for electronics plants, server rooms, and clean workshops.',
    'Износостойкое антистатическое покрытие для электроники, серверных и чистых помещений.',
    '高密度 PVC 材质，表面易清洁，支持批量铺装。建议配合导电胶和接地系统使用。',
    'High-density PVC with an easy-clean surface. Recommended with conductive adhesive and grounding.',
    'Плотный ПВХ с поверхностью, простой в уборке. Рекомендуется монтаж с токопроводящим клеем и заземлением.',
    12.80,
    '/mock/images/esd-floor-tile.svg',
    '["/mock/images/esd-floor-tile.svg"]'::jsonb,
    '[{"id":"size","label":{"zh":"尺寸","en":"Size","ru":"Размер"},"value":{"zh":"600 x 600 mm","en":"600 x 600 mm","ru":"600 x 600 мм"}},{"id":"thickness","label":{"zh":"厚度","en":"Thickness","ru":"Толщина"},"value":{"zh":"2.0 mm","en":"2.0 mm","ru":"2.0 мм"}}]'::jsonb,
    '["ESD","PVC","flooring"]'::jsonb,
    1,
    true,
    true
  ),
  (
    'epoxy-floor-kit',
    '11111111-1111-4111-8111-111111111111',
    '环氧防静电地坪套装',
    'ESD Epoxy Floor Coating Kit',
    'Комплект антистатического эпоксидного пола',
    '双组份环氧涂层，适合仓库、实验室和电子生产区域。',
    'Two-component epoxy coating for warehouses, labs, and electronics production areas.',
    'Двухкомпонентное эпоксидное покрытие для складов, лабораторий и электронного производства.',
    '包含底涂和面涂，施工后形成连续防尘表面。支持按项目面积报价。',
    'Includes primer and topcoat for a continuous dust-resistant surface. Project pricing available.',
    'Включает грунт и финишный слой для сплошной пылезащитной поверхности. Возможен расчет по площади.',
    58.00,
    '/mock/images/epoxy-floor-kit.svg',
    '["/mock/images/epoxy-floor-kit.svg"]'::jsonb,
    '[{"id":"coverage","label":{"zh":"覆盖面积","en":"Coverage","ru":"Покрытие"},"value":{"zh":"20-25 平方米/套","en":"20-25 m2/set","ru":"20-25 м2/комплект"}},{"id":"finish","label":{"zh":"表面效果","en":"Finish","ru":"Финиш"},"value":{"zh":"半光","en":"Semi-gloss","ru":"Полуглянцевый"}}]'::jsonb,
    '["epoxy","ESD","coating"]'::jsonb,
    2,
    true,
    true
  ),
  (
    'pu-mortar-floor-heavy-duty',
    '11111111-1111-4111-8111-111111111111',
    '重载聚氨酯砂浆地坪',
    'Heavy-duty PU Mortar Flooring',
    'Полиуретановое растворное покрытие для тяжелых нагрузок',
    '适合食品车间、冷库和重载叉车通道的耐冲击地坪。',
    'Impact-resistant flooring for food workshops, cold rooms, and heavy forklift lanes.',
    'Ударопрочное покрытие для пищевых цехов, холодильных камер и зон погрузчиков.',
    '耐温差、耐磨损，适合长期潮湿或频繁清洗环境。可按项目面积报价。',
    'Handles temperature changes and wear in wet or frequently washed environments. Project pricing available.',
    'Выдерживает перепады температуры и износ во влажных зонах с частой мойкой. Расчет по проекту.',
    42.50,
    '/mock/images/epoxy-floor-kit.svg',
    '["/mock/images/epoxy-floor-kit.svg","/mock/images/esd-floor-tile.svg"]'::jsonb,
    '[{"id":"thickness","label":{"zh":"建议厚度","en":"Recommended thickness","ru":"Рекомендуемая толщина"},"value":{"zh":"4-6 mm","en":"4-6 mm","ru":"4-6 мм"}},{"id":"area","label":{"zh":"适用区域","en":"Area","ru":"Зона применения"},"value":{"zh":"重载车间","en":"Heavy-duty workshop","ru":"Цех с высокой нагрузкой"}}]'::jsonb,
    '["PU","flooring","heavy-duty"]'::jsonb,
    3,
    false,
    true
  ),
  (
    'anti-slip-floor-tape',
    '11111111-1111-4111-8111-111111111111',
    '工业防滑警示胶带',
    'Industrial Anti-slip Warning Tape',
    'Промышленная противоскользящая сигнальная лента',
    '用于楼梯、坡道和设备周边的防滑与区域提示。',
    'Anti-slip marking for stairs, ramps, and equipment zones.',
    'Противоскользящая разметка для лестниц, пандусов и зон оборудования.',
    '背胶设计，施工简单。黄黑配色适合安全通道和危险边界标识。',
    'Self-adhesive backing for fast installation. Yellow-black color supports safety marking.',
    'Самоклеящаяся основа для быстрого монтажа. Желто-черная расцветка для зон безопасности.',
    6.90,
    '/mock/images/esd-floor-tile.svg',
    '["/mock/images/esd-floor-tile.svg"]'::jsonb,
    '[{"id":"width","label":{"zh":"宽度","en":"Width","ru":"Ширина"},"value":{"zh":"50 mm","en":"50 mm","ru":"50 мм"}},{"id":"length","label":{"zh":"长度","en":"Length","ru":"Длина"},"value":{"zh":"18 m/卷","en":"18 m/roll","ru":"18 м/рулон"}}]'::jsonb,
    '["anti-slip","safety","tape"]'::jsonb,
    4,
    false,
    true
  ),
  (
    'insulated-gloves-12kv',
    '22222222-2222-4222-8222-222222222222',
    '12kV 绝缘防护手套',
    '12kV Insulated Safety Gloves',
    'Изолирующие перчатки 12 кВ',
    '用于电气维护和设备检修的基础防护用品。',
    'Essential protection for electrical maintenance and equipment inspection.',
    'Базовая защита для обслуживания электрооборудования и проверки установок.',
    '柔韧橡胶材质，掌部纹理提升握持稳定性。使用前需按安全规范检查。',
    'Flexible rubber with textured palms for secure grip. Inspect according to safety rules before use.',
    'Гибкая резина с рельефной ладонью для надежного хвата. Перед применением требуется проверка.',
    18.50,
    '/mock/images/insulated-gloves.svg',
    '["/mock/images/insulated-gloves.svg"]'::jsonb,
    '[{"id":"voltage","label":{"zh":"耐压等级","en":"Voltage rating","ru":"Класс напряжения"},"value":{"zh":"12kV","en":"12kV","ru":"12 кВ"}},{"id":"sizes","label":{"zh":"尺码","en":"Sizes","ru":"Размеры"},"value":{"zh":"M / L / XL","en":"M / L / XL","ru":"M / L / XL"}}]'::jsonb,
    '["safety","electrical","gloves"]'::jsonb,
    5,
    false,
    true
  ),
  (
    'industrial-safety-goggles',
    '22222222-2222-4222-8222-222222222222',
    '防雾工业护目镜',
    'Anti-fog Industrial Safety Goggles',
    'Промышленные защитные очки против запотевания',
    '适合切割、打磨、喷涂和日常巡检使用。',
    'Eye protection for cutting, grinding, spraying, and daily inspection.',
    'Защита глаз при резке, шлифовке, окраске и ежедневных проверках.',
    '透明镜片带防雾涂层，弹性头带可调，适合长时间佩戴。',
    'Clear anti-fog lens with adjustable elastic strap for long shifts.',
    'Прозрачная линза с покрытием против запотевания и регулируемый ремешок.',
    4.60,
    '/mock/images/insulated-gloves.svg',
    '["/mock/images/insulated-gloves.svg"]'::jsonb,
    '[{"id":"lens","label":{"zh":"镜片","en":"Lens","ru":"Линза"},"value":{"zh":"透明防雾","en":"Clear anti-fog","ru":"Прозрачная против запотевания"}},{"id":"package","label":{"zh":"包装","en":"Package","ru":"Упаковка"},"value":{"zh":"12 副/盒","en":"12 pcs/box","ru":"12 шт/коробка"}}]'::jsonb,
    '["goggles","PPE","safety"]'::jsonb,
    6,
    true,
    true
  ),
  (
    'abs-safety-helmet',
    '22222222-2222-4222-8222-222222222222',
    'ABS 工程安全帽',
    'ABS Construction Safety Helmet',
    'Защитная каска ABS',
    '适合仓库、工地、设备安装和日常巡检。',
    'Head protection for warehouses, construction sites, installation, and inspection.',
    'Защита головы для склада, стройки, монтажа и обходов.',
    '轻量 ABS 外壳，旋钮调节头围，可搭配面屏和耳罩使用。',
    'Lightweight ABS shell with knob adjustment. Compatible with face shields and earmuffs.',
    'Легкий корпус ABS с регулировкой. Совместима с щитками и наушниками.',
    7.80,
    '/mock/images/insulated-gloves.svg',
    '["/mock/images/insulated-gloves.svg"]'::jsonb,
    '[{"id":"material","label":{"zh":"材质","en":"Material","ru":"Материал"},"value":{"zh":"ABS","en":"ABS","ru":"ABS"}},{"id":"colors","label":{"zh":"颜色","en":"Colors","ru":"Цвета"},"value":{"zh":"白 / 黄 / 蓝","en":"White / Yellow / Blue","ru":"Белый / Желтый / Синий"}}]'::jsonb,
    '["helmet","PPE","construction"]'::jsonb,
    7,
    false,
    true
  ),
  (
    'kn95-dust-mask-pack',
    '22222222-2222-4222-8222-222222222222',
    'KN95 防尘口罩 50只装',
    'KN95 Dust Mask Pack of 50',
    'Респираторы KN95 от пыли 50 шт',
    '适合仓储、打磨、包装和一般粉尘环境。',
    'Respiratory protection for warehousing, grinding, packing, and general dust environments.',
    'Защита дыхания для склада, шлифовки, упаковки и пыльных зон.',
    '五层过滤结构，鼻夹可调，单只独立包装，适合车间发放。',
    'Five-layer filter with adjustable nose clip. Individually packed for workshop distribution.',
    'Пятислойный фильтр, регулируемый носовой зажим, индивидуальная упаковка.',
    9.90,
    '/mock/images/insulated-gloves.svg',
    '["/mock/images/insulated-gloves.svg"]'::jsonb,
    '[{"id":"quantity","label":{"zh":"数量","en":"Quantity","ru":"Количество"},"value":{"zh":"50 只/盒","en":"50 pcs/box","ru":"50 шт/коробка"}},{"id":"filter","label":{"zh":"过滤结构","en":"Filter","ru":"Фильтр"},"value":{"zh":"五层","en":"5 layers","ru":"5 слоев"}}]'::jsonb,
    '["mask","PPE","dust"]'::jsonb,
    8,
    true,
    true
  ),
  (
    'led-work-light-50w',
    '33333333-3333-4333-8333-333333333333',
    '50W 便携式 LED 工作灯',
    '50W Portable LED Work Light',
    'Портативный LED прожектор 50 Вт',
    '高亮度工作照明，适合仓库、工地和夜间维修。',
    'Bright task lighting for warehouses, job sites, and night maintenance.',
    'Яркое рабочее освещение для складов, объектов и ночного ремонта.',
    '铝合金外壳，支架角度可调，支持多场景临时照明。',
    'Aluminum body with adjustable stand for temporary lighting in multiple scenarios.',
    'Алюминиевый корпус и регулируемая стойка для временного освещения разных зон.',
    24.00,
    '/mock/images/led-work-light.svg',
    '["/mock/images/led-work-light.svg"]'::jsonb,
    '[{"id":"power","label":{"zh":"功率","en":"Power","ru":"Мощность"},"value":{"zh":"50W","en":"50W","ru":"50 Вт"}},{"id":"ipRating","label":{"zh":"防护等级","en":"IP rating","ru":"Степень защиты"},"value":{"zh":"IP65","en":"IP65","ru":"IP65"}}]'::jsonb,
    '["LED","warehouse","lighting"]'::jsonb,
    9,
    false,
    true
  ),
  (
    'stackable-storage-bin',
    '33333333-3333-4333-8333-333333333333',
    '可堆叠零件周转箱',
    'Stackable Parts Storage Bin',
    'Штабелируемый контейнер для деталей',
    '适合仓库、车间和维修台的小件分类收纳。',
    'Small-parts organization for warehouses, workshops, and service benches.',
    'Организация мелких деталей для складов, мастерских и рабочих мест.',
    '前开口设计，拿取方便，可叠放节省空间。支持多色分类。',
    'Open-front design for easy picking. Stackable body saves space and supports color coding.',
    'Открытая передняя часть для удобного доступа. Штабелирование экономит место, доступны разные цвета.',
    3.20,
    '/mock/images/storage-bin.svg',
    '["/mock/images/storage-bin.svg"]'::jsonb,
    '[{"id":"size","label":{"zh":"尺寸","en":"Size","ru":"Размер"},"value":{"zh":"300 x 200 x 150 mm","en":"300 x 200 x 150 mm","ru":"300 x 200 x 150 мм"}},{"id":"package","label":{"zh":"包装","en":"Package","ru":"Упаковка"},"value":{"zh":"24 个/箱","en":"24 pcs/carton","ru":"24 шт/коробка"}}]'::jsonb,
    '["storage","warehouse","plastic"]'::jsonb,
    10,
    true,
    true
  ),
  (
    'laser-distance-meter',
    '33333333-3333-4333-8333-333333333333',
    '手持激光测距仪 60m',
    'Handheld Laser Distance Meter 60m',
    'Лазерный дальномер 60 м',
    '用于安装、仓储测量和施工现场快速测距。',
    'Fast measuring tool for installation, warehouse checks, and construction sites.',
    'Быстрый измерительный инструмент для монтажа, склада и строительных объектов.',
    '支持面积/体积计算，背光显示，便于单人快速记录尺寸。',
    'Supports area and volume calculation with backlit display for fast single-person measurement.',
    'Поддерживает расчет площади и объема, дисплей с подсветкой для быстрых измерений.',
    31.00,
    '/mock/images/laser-meter.svg',
    '["/mock/images/laser-meter.svg"]'::jsonb,
    '[{"id":"range","label":{"zh":"测量范围","en":"Range","ru":"Диапазон"},"value":{"zh":"0.05-60 m","en":"0.05-60 m","ru":"0.05-60 м"}},{"id":"accuracy","label":{"zh":"精度","en":"Accuracy","ru":"Точность"},"value":{"zh":"+/- 2 mm","en":"+/- 2 mm","ru":"+/- 2 мм"}}]'::jsonb,
    '["measurement","tool","laser"]'::jsonb,
    11,
    false,
    true
  ),
  (
    'ratchet-tie-down-strap',
    '33333333-3333-4333-8333-333333333333',
    '5吨棘轮捆绑带',
    '5T Ratchet Tie-down Strap',
    'Стяжной ремень с храповиком 5 т',
    '用于货物固定、仓储转运和车辆运输绑扎。',
    'Cargo securing strap for warehousing, handling, and vehicle transport.',
    'Ремень для фиксации груза на складе, при перемещении и перевозке.',
    '高强涤纶织带，棘轮收紧结构，双钩设计适合常见运输场景。',
    'High-strength polyester webbing with ratchet tensioner and double hooks.',
    'Прочная полиэстеровая лента с храповым механизмом и двумя крюками.',
    11.50,
    '/mock/images/storage-bin.svg',
    '["/mock/images/storage-bin.svg"]'::jsonb,
    '[{"id":"load","label":{"zh":"额定拉力","en":"Rated load","ru":"Нагрузка"},"value":{"zh":"5T","en":"5T","ru":"5 т"}},{"id":"length","label":{"zh":"长度","en":"Length","ru":"Длина"},"value":{"zh":"8 m","en":"8 m","ru":"8 м"}}]'::jsonb,
    '["cargo","strap","warehouse"]'::jsonb,
    12,
    false,
    true
  )
on conflict (id) do update
set
  category_id = excluded.category_id,
  name_zh = excluded.name_zh,
  name_en = excluded.name_en,
  name_ru = excluded.name_ru,
  description_zh = excluded.description_zh,
  description_en = excluded.description_en,
  description_ru = excluded.description_ru,
  detail_zh = excluded.detail_zh,
  detail_en = excluded.detail_en,
  detail_ru = excluded.detail_ru,
  price = excluded.price,
  cover_image = excluded.cover_image,
  images = excluded.images,
  specs = excluded.specs,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  is_featured = excluded.is_featured,
  is_active = excluded.is_active,
  updated_at = timezone('Asia/Shanghai', now());
